In [3]:
import numpy as np

In [11]:
# declare a vector
x = np.array([1, 2, 3])
y = np.array([1.1, 2.1, 3.1])   #vector so thuc
z = np.array([1, 2, 3], dtype=np.float64)   # ep kieu

In [12]:
print(type(x[0]))
print(type(y[0]))
print(type(z[0]))

<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [19]:
# declare 1-D array 

# vector 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
#vector 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
# tao mang co so chieu giong bien so x
np.zeros_like(x)

array([0, 0, 0])

In [24]:
# mang cap so cong 0 -> n-1
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
# cap so cong m -> n-1
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
# cap so cong cong sai d
np.arange(10,20, 2)

array([10, 12, 14, 16, 18])

In [35]:
#Xây dựng mảng các luỹ thừa của 2 nhỏ hơn 1025, bao gồm cả 1 = 2**0. 

(np.ones(11, dtype=np.int64) + 1)**np.arange(11)

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

In [40]:
# Xây dựng mảng gồm 10 phần tử, trong đó 9 phần tử đầu bằng 3, phần tử cuối cùng bằng 1.5.
x = (np.zeros(10)+3)
x[9] = 1.5
x

array([3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 1.5])

In [46]:
x = np.array([1,2,3,4,5])
# size array : return tuple 
x.shape
size = x.shape[0]
size

5

In [47]:
# doc nhieu phan tu 1 lan 
y = np.array([11, 23, 223, 23, 464, 6565, 232, 2234, 243, 343])
indexs = [0,2,4]  #list
y[indexs]

array([ 11, 223, 464])

In [50]:
# read array 
a = np.array([1,2,4,5,6,7,8,3434,34,3,4])
a[:3] #return first three elements 

array([1, 2, 4])

In [56]:
a[-3:] # return last three elements 

array([34,  3,  4])

In [58]:
a[1:4]  #return elements with indexs 1,2,3

array([2, 4, 5])

In [60]:
a[1:] #return elements from 1 to end

array([   2,    4,    5,    6,    7,    8, 3434,   34,    3,    4])

In [63]:
# change value 
a[[1,3,5]] = 1 # <=> a[1]=a[3]=a[5] = 1
a

array([   1,    1,    4,    1,    6,    1,    8, 3434,   34,    3,    4])

In [66]:
# change last three elements
a[-3:] = np.array([10, 11, 12])
a

array([   1,    1,    4,    1,    6,    1,    8, 3434,   10,   11,   12])

In [112]:
# return all element with EVEN indexs (chi muc  chan )
# a[start:stop:step]
a[::2]      #a[0:end: step = 2]

array([2. , 1.5])

In [ ]:
# return all element with ODD indexs (chi muc  le )
a[1::2]

In [70]:
# reverse an array 
a[::-1]

array([  12,   11,   10, 3434,    8,    1,    6,    1,    4,    1,    1])

In [117]:
# Cho trước một số tự nhiên n. Tạo một mảng có n phần tử mà các phần tử có chỉ số chẵn (bắt đầu từ 0) là một cấp số cộng bắt đầu từ 2,
#công sai bằng -0.5; các phần tử có chỉ số lẻ bằng -1.
import math
n = 5
a = np.zeros(n)
numEvenElm = math.ceil(n/2)
numOddElm = math.floor(n/2)
a[::2] = np.arange(2, 2+(-0.5)*numEvenElm, -0.5)
a[1::2] = np.ones(numOddElm)
a

array([2. , 1. , 1.5, 1. , 1. ])

## Tính toán giữa các mảng một chiều và số vô hướng
### mảng 1 chiều x với một số vô hướng a : a ? x (? ~ +, - , * , /, **)

In [4]:
x = np.array([1, 2, 3, 4, 5])
a = 3

In [5]:
x ** a

array([  1,   8,  27,  64, 125])

In [20]:
#Viết hàm số tính tổng trị tuyệt đối các phần tử của một mảng một chiều.
x = np.array([1,-2,3,-4])
np.sum(np.abs(x))



10

In [27]:
#Hãy lập trình hàm softmax.
v = np.array([1,3,5,7])  # a vector
def softmax(z):
    e_z = np.exp(z) # a array e

    a =  e_z / e_z.sum()
    return a

print(softmax(v))

[0.00214401 0.0158422  0.11705891 0.86495488]


In [33]:
# Tích vô hướng của hai vectors (cung so phan tu)- Norm 2
x = np.arange(3)
y = np.ones(3)
tvh = np.sum(x*y)
tvh

3.0

In [36]:
# Cach 2: tinh tich vo huong
x.dot(y)

np.dot(x,y)

3.0

In [40]:
# Tinh norm 2
vt = np.array([1,2,3,4,5])
norm2 = np.sum(np.power(vt,2))
norm2

55

In [47]:
# min, max, armin, argmax của mảng một chiều
arr = np.array([3,5,2,6,7,2,9])
print(np.min(arr))
print(np.max(arr))
print(arr.min())
print(arr.max())

print(np.argmin(arr))
print(np.argmax(arr))   #index of max element

2
9
2
9
2
6
